### ISSUE TITLE
Confidence interval of mean: Should Student’s t be used instead of norm?

### ISSUE THREAD

**Issue by constructor-s** [jaketmp/pyCompare#10]
https://github.com/jaketmp/pyCompare/blob/05e26d1398b00e4e4fef2504ec1e588bfa958c9c/pyCompare/_calculateConfidenceIntervals.py#L28

Based Carkeet's 2015 description I think a more accurate representation of the mean CI would be:

```python
scipy.stats.t.interval(confidenceInterval, n-1, loc=md, scale=sem)
```

where `confidenceInterval = 0.95` and `sem = sd/np.sqrt(n)` is the standard error of the mean

In fact if we follow `scipy.stats.sem` a better implementation might be `sd/np.sqrt(n-1)`, but this is contrary to what Carkeet 2015 described.

A useful discussion is here: [Compute a confidence interval from sample data](https://stackoverflow.com/a/34474255/6610243)

Would like to hear your thoughts. Thank you for creating this wonderful library!

**Comment by jaketmp** [comment]
Thanks for your comment - I think you're right and looking back this stems from a bad reading of the example Matlab code in the paper.

I'll take a closer look at push fix when I have a chance.

**Comment by constructor-s** [comment]
Looks great thanks for putting this in! Any chance the [PyPI](https://pypi.org/project/pyCompare/#history) and/or [Anaconda](https://anaconda.org/conda-forge/pycompare/files) packages can be updated? Probably also need to bump the version to `1.6` or even `2.0` since this is a bit of a "breaking" change?

**Comment by jaketmp** [comment]
I was actually thinking this is a patch as it's really just fixing the previous broken approach.

The CI pipeline is a bit broken at the mo - will push out a release to PyPi as soon as I can fix it.

**Comment by jaketmp** [comment]
1.5.2 is out on PyPi now
