### ISSUE TITLE
Publish pyCompare 1.3.1 sdist on PyPI

### ISSUE THREAD

**Issue by hoechenberger** [jaketmp/pyCompare#5]
Hello, could you please upload the sdist to PyPI too? Currently, only a wheel is available. Thank you!

**Comment by jaketmp** [comment]
Hmm - Travis is supposed to push a sdist to PyPI - I'm not really sure why it's failed in the case of `1.3.1`, I'll have to investigate.

**Comment by hoechenberger** [comment]
Thanks :)

**Comment by jaketmp** [comment]
Fixed in 43948c6202535f16151b13dbea77253d35dab0ff.
