### ISSUE TITLE
Plot differences as a percentage

### ISSUE THREAD

**Issue by ltirrell** [jaketmp/pyCompare#6]
Would it be possible to add a parameter to plot the difference as a percentage, instead of just raw difference values? 

[Here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4470095/#__sec6title) is an example showing this, where the y-axis would show `((data1 - data2) / mean) * 100`.

I could also submit a PR if that is appropriate

**Comment by jaketmp** [comment]
That looks simple enough - happy to accept a PR, or leave this here and I'll implement next time I've time to make changes.

(it feels like the LoA should be proportional to value here, but I suppose that is just one interpretation of the plot)
