### ISSUE TITLE
small figure sizes

### ISSUE THREAD

**Issue by philippaichinger** [jaketmp/pyCompare#9]
dear all,
I am trying to export a small figure (4x3 inches). In such a small figure, the labels of the x and y axes appear to be outside of the canvas. Is there a recommended workaround?
Alternatively, I would also be fine with exporting a larger figure (e.g., ~7x4), while increasing all font sizes.

thanks a lot.

best, philipp

**Comment by jaketmp** [comment]
Hi Philipp - using the test data from the notebook in the repository(`pyCompare-Demo.ipynb`), and running `pyCompare.blandAltman(method1, method2, figureSize=(4,3))`, I get a normal looking figure:
![Unknown](https://user-images.githubusercontent.com/738903/91174514-4c426c00-e6d7-11ea-8b42-75ea2a846b1c.png)
Can you share and example / the data you are plotting?

**Comment by philippaichinger** [comment]
Hi,

that's what I got:

import pyCompare as pc

F0 = [267, 364, 267, 250, 364, 333, 333, 308, 235, 286, 286, 308, 308, 
               308, 250, 308, 286, 235, 286, 250, 308, 267, 308, 286, 308]

F0_ovrln = [261.0,
		369.0,
		262.0,
		243.0,
		352.0,
		274.0, 
		320.0,
		302.0, 
		224.0,
		267.0,
		277.0,
		350.0, 
		289.0,
		290.0, 
		236.0, 
		277.0,
		264.0,
		199.0,
		266.0, 
		235.0,
		280.0, 
		257.0,
		372.0,
		265.0,
		308.0] ;
    
            
Delta_T_LR = [-0.188, 0.167, -0.0625, -0.667, 0.286, 0.575, 0.325, 0.361, 
              0.722, 0.477, 0.438, 0.306, 0.417, -0.4, -0.917, -0.325,
              -0.611, -1, -0.575, -1.22, -0.531, -1.08, -0.556, -0.95, -0.675];

Delta_T_LR_ovrln = [-0.189,
		0.159, 
		-0.0756,
		-0.612, 
		0.272, 
		0.302,
		0.324,
		0.35,
		0.499, 
		0.491,
		0.295,
		0.801,
		0.596,
		-0.305,
		-0.925, 
		-0.302,
		-0.438, 
		-0.975,
		-0.567, 
		-0.454,
		-0.469, 
		-0.537,
		-1.28,
		-0.627,
		-0.627];
             
Delta_T_AP = [-0.375, -0.917, -0.25, -0.917, -0.0714, -0.15, 0.175, 0.278, 0,
              -0.5, -0.125, 0.417, 0.222, 0.05, 0.0, 0.025, -0.0833, -0.125,
              0.275, 0.0, 0.156, -0.0556, 0.278, 0.3, 0.275];

Delta_T_AP_ovrln = [-0.37,
-0.601,
-0.257,
-0.741,
-0.187, 
-1.12,
0.181,
0.285,
0.172,
-0.454,
-0.181,
1.03,
0.46,
0.168,
0.461,
0.181,
-0.34,
-0.306,
0.454, 
0.287,
0.28,
-0.272,
-1.63,
0.559,
0.454]; 
    
![Delta_T_AP_BlandAltman](https://user-images.githubusercontent.com/6513145/91176806-14d9bc80-e6e3-11ea-818c-96c301e623e8.png)
![Delta_T_LR_BlandAltman](https://user-images.githubusercontent.com/6513145/91176808-15725300-e6e3-11ea-95f5-7c4998ee7241.png)
![F0_BlandAltman](https://user-images.githubusercontent.com/6513145/91176810-160ae980-e6e3-11ea-816a-2336925c91ae.png)



#%% Create Bland Altman Plots
pc.blandAltman(F0,F0_ovrln,limitOfAgreement=1.96,
            confidenceInterval=95,
            confidenceIntervalMethod='approximate',
            detrend=None,
            percentage=False,
            savePath='F0_BlandAltman.png',
            figureFormat='png',
            figureSize=(4,3))
pc.blandAltman(Delta_T_LR,Delta_T_LR_ovrln,limitOfAgreement=1.96,
            confidenceInterval=95,
            confidenceIntervalMethod='approximate',
            detrend=None,
            percentage=False,
            savePath='Delta_T_LR_BlandAltman.png',
            figureFormat='png',
            figureSize=(4,3))
pc.blandAltman(Delta_T_AP,Delta_T_AP_ovrln,limitOfAgreement=1.96,
            confidenceInterval=95,
            confidenceIntervalMethod='approximate',
            detrend=None,
            percentage=False,
            savePath='Delta_T_AP_BlandAltman.png',
            figureFormat='png',
            figureSize=(4,3))

**Comment by jaketmp** [comment]
It's interesting - this only seems to happen when writing to a file - not drawing interactively:
![Unknown-2](https://user-images.githubusercontent.com/738903/91188870-b2d08580-e6e9-11ea-9d31-cb47e9696924.png)
I'm not really sure how to account for this as the only difference is calling `plt.show()` vs `fig.savefig()`.

I'll uploaded a v1.5.0 in ba82a10 that adds the option to pass in and return an axis handle, so you can style that directly:
```
fig, ax = matplotlib.pyplot.subplots()
import numpy
ax1 = pyCompare.blandAltman(numpy.random.rand(100)*100+100,
                           numpy.random.rand(100)*50+100,
                           confidenceIntervalMethod='approximate',
                           ax=ax)
```

**Comment by jaketmp** [comment]
Closing now 1.5.0 is available in PyPi.

**Comment by philippaichinger** [comment]
thanks!
